### ISSUE TITLE
compile app error

### ISSUE THREAD

**Issue by lost22git** [athena-framework/athena#302]
* version
```
dependencies:
  athena:
    github: athena-framework/framework
    version: ~> 0.18.0
```

* error msg;

```
In lib/athena-routing/src/ext/regex.cr:3:44

 3 | fun jit_match = pcre2_jit_match_8(code : Code*, subject : UInt8*,
 length : LibC::SizeT, startoffset : LibC::SizeT, options : UInt32, ma
tch_data : MatchData*, mcontext : MatchContext*) : Int
                                              ^---
Error: undefined constant Code

```
