### ISSUE TITLE
Support Windows in Athena Console

### ISSUE THREAD

**Issue by dsisnero** [athena-framework/athena#386]
Trying to run the simplest athena-console app

Error: Athena::Console component does not support Windows yet.

**Comment by Blacksmoke16** [comment]
This will be resolved in next release, for now you can pin the dependency to commit `c12f07b5a11c0d116acfa06d85d2062d9e9d211d`, but will require a minimum of Crystal 1.11.

If you're getting this error when using the entire framework, you can do like:
```yaml
# shard.yml
dependencies
  athena:
    github: athena-framework/framework
    commit: 8f0157e1cbbd4c5da2087b5a05bb1ff1182619ff
```

```yaml
# shard.override.yml
dependencies:
  athena-console:
    github: athena-framework/console
    commit: c12f07b5a11c0d116acfa06d85d2062d9e9d211d
```

Then run `shards update` and should be good to go, at least until the next release makes all this unneeded.
